name: Release

on:
  workflow_dispatch:
    inputs:
      RELEASE:
        description: "Is it a release?"
        required: true
        default: "false"
  
env:
  VERSION_SUFFIX: $(${env:GITHUB_REF} -replace '.*?/', '')
  ENVIRONMENT: ''
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Set env to staging
        if: endsWith(github.ref, '/add_packages_and_release_in_actions') && github.event.inputs.RELEASE.RELEASE == 'false'
        run: |
         echo "::set-env name=ENVIRONMENT::staging"
      - name: Set env to production
        if: endsWith(github.ref, '/master')
        run: |
         echo "::set-env name=ENVIRONMENT::production"
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Branch name
        run: echo "running on branch ${{env.VERSION_SUFFIX}} ENVIRONMENT ${{env.ENVIRONMENT}} release ${{github.event.inputs.RELEASE}}"
      - name: run number
        run: echo "Build number is ${env:GITHUB_RUN_NUMBER} ${env:GITHUB_REF} actions ${env:GITHUB_ACTIONS} ${env:BUILD_NUMBER} $env:BUILD_BUILDID ${Build.BuildNumber} ${env:Build.BuildNumber} workspace ${env:GITHUB_WORKSPACE}"
      - name: Build
        run: docker build -t tedmiston/tag-example:${GITHUB_REF##*/} .
